### ISSUE TITLE
code for testing trained model

### ISSUE THREAD

**Issue by wanghuimu** [iclavera/learning_to_adapt#1]
Hello:
     I read your codes and your codes are written very well! But in the code ‘run_grbal.py’ of ‘run_scripts’ folder, I only found codes for training the model and I didn’t find the codes for testing the trained model in the environments like AntEnv, would you mind uploading the codes file for testing? 
                                                                                                                Thank you~

**Comment by dingchenghu** [comment]
So is there a separate code to test the trained model?

**Comment by shafeef901** [comment]
I know I'm pretty late now, but the code to test the trained model is in `experiment_utils/sim_policy.py`. Let me know if you have been able to train the model successfully.
